export const products = [
  {
    id: 1,
    name: "Product name 1",
    img1: "/image.webp",
    img2: "/image2.webp",
    description:
      "Laptop Acer Extensa to bardzo uniwersalne urządzenie. Szukasz sprzętu, który posłuży Ci do pracy biurowej, nauki, czy jako domowe centrum rozrywki? Ten laptop sprawdzi się w każdym z tych zadań. Jego zaawansowane komponenty zapewnią Ci komfortową obsługę każdego dnia. Praca z arkuszami kalkulacyjnymi od teraz będzie bardziej wygodna dzięki dostępnej klawiaturze numerycznej. Gdy przyjdzie pora na zasłużony relaks, możesz odprężyć się przy ulubionym serialu czy prostej grze. Dołącz do szczęśliwych posiadaczy laptopa Acer Extensa i ciesz się jego uniwersalnością.",
    price: 1000,
    ratingTotal: 34,
    reviewsCount: 7,
    stock: 0,
  },
  {
    id: 2,
    name: "Product name 2",
    img1: "/image.webp",
    img2: "/image2.webp",
    description:
      "Laptop Acer Extensa to bardzo uniwersalne urządzenie. Szukasz sprzętu, który posłuży Ci do pracy biurowej, nauki, czy jako domowe centrum rozrywki? Ten laptop sprawdzi się w każdym z tych zadań. Jego zaawansowane komponenty zapewnią Ci komfortową obsługę każdego dnia. Praca z arkuszami kalkulacyjnymi od teraz będzie bardziej wygodna dzięki dostępnej klawiaturze numerycznej. Gdy przyjdzie pora na zasłużony relaks, możesz odprężyć się przy ulubionym serialu czy prostej grze. Dołącz do szczęśliwych posiadaczy laptopa Acer Extensa i ciesz się jego uniwersalnością.",

    price: 1000,
    ratingTotal: 34,
    reviewsCount: 7,
    stock: 99,
  },
  {
    id: 3,
    name: "Product name 3",
    img1: "/image.webp",
    img2: "/image2.webp",
    description:
      "Laptop Acer Extensa to bardzo uniwersalne urządzenie. Szukasz sprzętu, który posłuży Ci do pracy biurowej, nauki, czy jako domowe centrum rozrywki? Ten laptop sprawdzi się w każdym z tych zadań. Jego zaawansowane komponenty zapewnią Ci komfortową obsługę każdego dnia. Praca z arkuszami kalkulacyjnymi od teraz będzie bardziej wygodna dzięki dostępnej klawiaturze numerycznej. Gdy przyjdzie pora na zasłużony relaks, możesz odprężyć się przy ulubionym serialu czy prostej grze. Dołącz do szczęśliwych posiadaczy laptopa Acer Extensa i ciesz się jego uniwersalnością.",

    price: 1000,
    ratingTotal: 34,
    reviewsCount: 7,
    stock: 99,
  },
];

export const reviews = [
  {
    id: 1,
    productId: 1,
    rating: 5,
    content: "Great product",
    userName: "John Doe",
    date: "20-04-2024 21:37",
  },
  {
    id: 2,
    productId: 1,
    rating: 5,
    content: "Great product",
    userName: "John Doe",
    date: "20-04-2024 21:37",
  },
  {
    id: 3,
    productId: 1,
    rating: 5,
    content: "Great product",
    userName: "John Doe",
    date: "20-04-2024 21:37",
  },
  {
    id: 4,
    productId: 2,
    rating: 5,
    content: "Great product",
    userName: "John Doe",
    date: "20-04-2024 21:37",
  },
  {
    id: 5,
    productId: 2,
    rating: 5,
    content: "Great product",
    userName: "John Doe",
    date: "20-04-2024 21:37",
  },
  {
    id: 6,
    productId: 2,
    rating: 5,
    content: "Great product",
    userName: "John Doe",
    date: "20-04-2024 21:37",
  },
  {
    id: 7,
    productId: 3,
    rating: 5,
    content: "Great product",
    userName: "John Doe",
    date: "20-04-2024 21:37",
  },
  {
    id: 8,
    productId: 3,
    rating: 5,
    content: "Great product",
    userName: "John Doe",
    date: "20-04-2024 21:37",
  },
  {
    id: 9,
    productId: 3,
    rating: 5,
    content: "Great product",
    userName: "John Doe",
    date: "20-04-2024 21:37",
  },
];
